"""empty message

Revision ID: 1329656b7842
Revises: 43e9aecc2c34
Create Date: 2015-06-05 16:35:25.876110

"""

# revision identifiers, used by Alembic.
revision = '1329656b7842'
down_revision = '43e9aecc2c34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
